### ISSUE TITLE
Catergory Buttons Styling Does Not Work

### ISSUE THREAD

**Issue by OdiousImp2604** [nwg-piotr/nwg-drawer#6]
The styling for category buttons does not work. The buttons continue to take the styling from the buttons.
`
nwg-drawer version 0.1.3`

DRAWER.CSS
```
window {
    background-color: rgba (36, 47, 79, 0.95);
    color: #eeeeee
}

entry {
   box-shadow: 0 0 6 5 #2e3440;
   background-color: #3b4252;
   border: none;
   border-radius:10px;
}

button {
    box-shadow: 0 0 6 5 #2e3440;
    background-color: #3b4252;
    border: none;
    border-radius:5px;
    margin: 4px;
}

category-button {
    background-color: transparent;
    padding: 1px;
}    
    

button:hover {
    background-color: rgba(129,161,193,0.7);
}

button:focus {
    background-color: #5e81ac;
}

#pinned-box {
    padding-bottom: 10px;
    border-bottom: 1px dotted gray
}

#files-box {
    padding: 10px;
    border: 1px dotted gray;
}    

```

**Comment by nwg-piotr** [comment]
You missed `#`. Should be:

```css
#category-button {
    background-color: transparent;
    padding: 1px;
}
```

**Comment by OdiousImp2604** [comment]
No change.

**Comment by nwg-piotr** [comment]
Works well for me. BTW: you should also use use `px` in lines 7 and 14.

```css
window {
    background-color: rgba (36, 47, 79, 0.95);
    color: #eeeeee
}

entry {
   box-shadow: 0 0 6px 5px #2e3440;
   background-color: #3b4252;
   border: none;
   border-radius:10px;
}

button {
    box-shadow: 0 0 6px 5px #2e3440;
    background-color: #3b4252;
    border: none;
    border-radius:5px;
    margin: 4px;
}

#category-button {
    background-color: transparent;
    padding: 1px;
}    
    

button:hover {
    background-color: rgba(129,161,193,0.7);
}

button:focus {
    background-color: #5e81ac;
}

#pinned-box {
    padding-bottom: 10px;
    border-bottom: 1px dotted gray
}

#files-box {
    padding: 10px;
    border: 1px dotted gray;
}
```

![2021-07-11-235512_screenshot](https://user-images.githubusercontent.com/20579136/125211103-43816700-e2a4-11eb-801c-01e1418b4dcb.png)

**Comment by OdiousImp2604** [comment]
Using the exact the drawer.css you gave me it still does work. This is installed from the Chaotic-AUR - up to date with the repo. I previously updated from the version below. 

This is what shows after launching it in terminal. 
```
lang: en_GB
Found 113 desktop files
Skipped 0 duplicates; 16 .desktop entries hidden by "NoDisplay=true"

(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:7:20: Not using units is deprecated. Assuming 'px'.

(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:7:22: Not using units is deprecated. Assuming 'px'.

(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:14:21: Not using units is deprecated. Assuming 'px'.

(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:14:23: Not using units is deprecated. Assuming 'px'.
Using style from /home/aryan/.config/nwg-panel/drawer.css

(nwg-drawer:3564): Gtk-CRITICAL **: 18:54:50.185: gtk_flow_box_set_max_children_per_line: assertion 'n_children > 0' failed
(0x56361539a718,0xc000217640)
(0x56361539a718,0xc000217b80)
(0x56361539a718,0xc000217c50)
Using XDG user dirs from /home/aryan/.config/user-dirs.dirs

** (nwg-drawer:3564): WARNING **: 18:54:50.372: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
UI created in 300 ms. 
```

Thank you for your patience and 
thank you for all your quick responses!

**Comment by nwg-piotr** [comment]
These warnings:

```text
(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:7:20: Not using units is deprecated. Assuming 'px'.

(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:7:22: Not using units is deprecated. Assuming 'px'.

(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:14:21: Not using units is deprecated. Assuming 'px'.

(nwg-drawer:3564): Gtk-WARNING **: 18:54:50.154: Theme parsing error: drawer.css:14:23: Not using units is deprecated. Assuming 'px'.
```

come from your version of the css file, and should be absent when using my fixed version.

**Comment by nwg-piotr** [comment]
Closed unintentionally. What I fixed should have nothing to do with your issue.

**Comment by OdiousImp2604** [comment]
Sorry for the wait. No idea why those error still show. I'm using your exact drawer.css. 

I'm assuming the problem is with me rather than something with nwg-drawer. Any ideas on any debug I could attempt etc...

**Comment by nwg-piotr** [comment]
Try another GTK theme to learn if it changes something.
